### ISSUE TITLE
Prevent hardcoding of IAM pass role

### ISSUE THREAD

**Issue by calvinlfer** [ukayani/ecs-jenkins#1]
Currently, the following line hardcodes the IAM role to a particular AWS account 
https://github.com/ukayani/ecs-jenkins/blob/6db2633f5870e5b77ba83f77865fedd2e55e4a7e/ECSJenkins.yml#L173

Would this work instead?
```yaml
Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/*' 
```

**Comment by ukayani** [comment]
Fixed
